### ISSUE TITLE
Promotions

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#11]
- [x] Let's bring in "Load More" for Promotions once I add more promotions into it
- [x] ~~Do you think Promotions should be attached to a Tapak too? If it's not attached to a Tapak, meaning it will appear in any Promotions listing eg: it's a General promotion. If it's attached to a Tapak, it will appear in any listing plus that Tapak's profile only~~
- [x] What's the size to use to upload Promotion?

I'm interested to see the next update for the Promotions section as from what I can see now on the backend, only Admin can upload Promotions and then we categorize them by sizes. That's a bit different from the user specs

**Comment by aienzaini** [comment]
Size should be automatically adjusted. You just need to upload the image.

**Comment by aienzaini** [comment]
I don't think Promotions should be attached to Tapak. The relationship should be "Promotions with FT". Tapak promotions will be taken from FT having promo and available at that Tapak.

**Comment by iwanikhalid** [comment]
Ok awesome @aienzaini you know better hihi

**Comment by iwanikhalid** [comment]
@aienzaini can we remove the Tapak field in Promotions since we are not attaching promo to tapak?

**Comment by iwanikhalid** [comment]
Promotions work awesome @aienzaini . Check out the PAST tab, I've filled up 10 promos. The Load More swaps the positions and promos awesomely.

**A couple of fixes**

- [ ] The box highlighted in red isn't stretched until the end. This happened on both Ongoing & Past tabs

![promotions-pull-me](https://cloud.githubusercontent.com/assets/751716/16084858/d36dc668-334c-11e6-9ef0-82239866244a.jpg)

- [ ]  Can we remove the Tapak field in Promotions WP Admin since we are not attaching promo to tapak?

- [ ] AR Coconut Shake doesn't have any Booking. Let's not allow them to post Promotion. Now their promo happily sits in the Ongoing tab

I think with the fixes above, we can close Promotion for good and just wait for User Roles to be added and re-test using actual FTO account.

**Comment by aienzaini** [comment]
Might need to edit and re-save all Tapak as i have just removed the field (updating any fields seem to update the key to save data).

**Comment by iwanikhalid** [comment]
@aienzaini there seems to be a bug on Promotions today. It seems that the promos are not loading in all the boxes, some boxes are as if on 'no entry mode!'

- [ ] Past tab: 457x522
- [ ] Ongoing tab: 221x194, 226x194 and 457x522

**Comment by aienzaini** [comment]
@iwanikhalid I need to make it more random across all boxes. Will update the logic today

**Comment by iwanikhalid** [comment]
Ok noted @aienzaini

**Comment by iwanikhalid** [comment]
Closing this for the time being as all issues have been resolved
