### ISSUE TITLE
Homepage > General Issues

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#12]
- [x] Can we display the Tapak logo in frontpage header.small, on the top left? If possible, make it look like it's flying from the Slideshow to the top left of header.small 
- [x] Is the About Us section on frontpage using the font in PSD? My view doesn't seem to look like it

**Comment by aienzaini** [comment]
Can we not have it fly from the Slideshow because if the video is being show, there wont be any logo. So it's kind of weird. What do u think? Can we just have it shown there?

**Comment by iwanikhalid** [comment]
@aienzaini Okeh, I agree. Let's do that!
