### ISSUE TITLE
FT Profile

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#14]
- [x] WP won't let me create a FT unless a Tapak is attached to it. According to User Specs, FT Profile can be created and have a visible Profile URL but it won't be listed in the website until it books a Slot (ie: attach itself to a Tapak)
- [x] FT Intro and Video doesn't seem to work. I've added image and YouTube URL for Mat Rock
- [x] Have to advise logo size to upload for Tapak and FT Profile in order to appear nicely at all times, everywhere in the website
- [x] FT Profile: Instagram URL doesn't work, the URL is missing a / 
- [x] Add format helper for FT Profile > Telephone field eg: +603 9202 1111

**Comment by aienzaini** [comment]
I have removed the Tapak field for FT. It should be taken dynamically from Booking.

**Comment by aienzaini** [comment]
Logo size should be adjusted automatically, minimum is 200x200 px. If it doesnt show properly, let me know. I will adjust the logic.

**Comment by iwanikhalid** [comment]
@aienzaini Tapak field is still here on my screen! In case you missed out uploading some files to the dev site hehe

**Comment by iwanikhalid** [comment]
Ok @aienzaini it's gone hehe thanks!

**Comment by iwanikhalid** [comment]
**Continuation of Issues**

- [ ] I still see the Tapak field in WP Admin: FT add/edit screen
- [ ] Slideshow on FT Profile: Video works! But image not yet. If possible, make the video play in full width and leave the sound on
- [ ] Can we enable FTO to upload unlimited video and image to the slideshow?
