### ISSUE TITLE
Tapak Profile

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#15]
- [x] Have to advise size logo for Tapak and FT Profile in order to appear nicely at all times, everywhere in the website
- [x] Tapak profile: Waze & 4sq has the fields been added?
- [x] Tapak profile: Google Map is showing the way from KLCC to the active Tapak? For testing kan?  Looks so sick, Aien this bit of the profile. Can't wait for it to start detecting user's actual location
~~[Solved[ Dah add new Tapak but tak appear kat frontage "Explore our Tapak" yet~~

**Comment by aienzaini** [comment]
Waze will follow the coordinate that you put for the tapak. 4sq field has been added.

**Comment by aienzaini** [comment]
Tapak and FT Profile, minimum is 200x200. The rest should be cropped automatically in the middle.

**Comment by iwanikhalid** [comment]
The fixes above have been tested and verified, awesome!

Just one question, is the Map picking up user's location yet? I still see it showing directions from KLCC @aienzaini

**Comment by iwanikhalid** [comment]
- [ ] Open up 4sq in new tab
- [ ] Enable admin to insert unlimited Video and Image for the slideshow
- [ ] Google Map to detect user's location

**Comment by iwanikhalid** [comment]
The issues above have been fixed and will be put to a [test](https://github.com/iwanikhalid/tapak/issues/23) today!

Detecting location: refer below

> Retrieving current location requires HTTPS. Can you arrange it in LIVE? Reference: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins
