### ISSUE TITLE
WP Admin

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#17]
- [ ] How difficult it is for us to add helper text for each fields? I like the way you put helpter text for Coordinates for example. I think we need these helper text for all the fields. Let me know if it's possible and I will prepare them for all the fields in the website

**Comment by aienzaini** [comment]
Easy, go here http://52.163.95.207/tapak/wp-admin/edit.php?post_type=acf > click on the custom field group > edit the field > put the helper in Field Instructions > Save!

**Comment by iwanikhalid** [comment]
Okeh, thanks @aienzaini
