### ISSUE TITLE
Homepage > Explore Our Tapak : Tapak info box breaking 

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#18]
I think we can truncate the address but not the title? Or truncate both title and address for this kinda issue. Check out screenshot below

![explore-our-tapak-bug](https://cloud.githubusercontent.com/assets/751716/15989062/9ca4e506-309c-11e6-9f1d-3c52226fbe9f.jpg)

**Comment by iwanikhalid** [comment]
Hmm truncate the address je lah!

**Comment by aienzaini** [comment]
Fixed!

**Comment by iwanikhalid** [comment]
@aienzaini Thanks for the fix!

However, we've lost the opening hours on that pop up. Bring it baaack! Hehehe. Or any reasons we're removing it? Tak muat box maybe? Let me know okie!

Also, the other Tapaks are missing from the map. Or do I need to delete all mock data and recreate them?

**Comment by aienzaini** [comment]
@iwanikhalid Sorry, not sure why the opening hours lost but if you open one by one and save them, that should fix it. Also, i have made the map to auto center by using all marker locations.

**Comment by iwanikhalid** [comment]
@aienzaini ok noted! If that's the case no worries
