### ISSUE TITLE
To update User Specs & Design Briefs

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#22]
@aienzaini After you've set the foundation for the website and starting to work on the User Roles and other Details of the website

- [x] can you highlight in green the items that are done in the [User Specs](https://docs.google.com/document/d/1b28nW3_6a7Qk-TrbwQl9Wng1UZTFxsNoZKJ25hIB5B0/edit) so we both can monitor what's done / what's not from that document

If there's any spec you changed while developing, just leave a Comment next to the item for our reference

---

And my task is to edit the design briefs

- [x] [Food truck profile](https://docs.google.com/document/d/15O0mPoOsa7172QyTht-_J3h_jI-IUPWIngs5a-INwZ0/edit)
- [x] [Tapak profile](https://docs.google.com/document/d/1ExxbQZcbDgcKobdv_GcokHDKan0hO-3NbLxwYa9Pzn8/edit)
- [x]  [Homepage](https://docs.google.com/document/d/1fDfC1aFkxD68i8OeyNWpjh4qimgYsJUQ51c2qc2ZTEQ/edit)

**Comment by iwanikhalid** [comment]
I've checked the design briefs and highlighted 

- in green items that have been developed 
- in yellow items that need to be retested
- in red items that haven't been developed
- in blue items that need enhancement

Will post red and blue items in Issues later

**Comment by iwanikhalid** [comment]
@aienzaini can you block some time tomorrow to highlight in green the items that are done in the User Specs so we're both aware of what's done and what's not. Thankies!

**Comment by aienzaini** [comment]
@iwanikhalid Just finished going through the list!

**Comment by iwanikhalid** [comment]
@aienzaini awesome! will check it out!

**Comment by iwanikhalid** [comment]
Ok @aienzaini dah went through your comments. Agree with all! 

That Notification thingy is SWEET!!!
