### ISSUE TITLE
Testing & Debugging 1

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#23]
**Testing will be done today in the next hours**

- will be recreating 3 FTs by using Admin. And save 3 more when testing with actual User Role that is FTO himself registers its' FT
- will be recreating 3 Tapaks for now. and saving 3 more after User Roles have been added

---

**Slideshow test**
- will test [Slideshow](https://github.com/iwanikhalid/tapak/issues/19) : Unlimited and single - test vdeo plays etc: on hover, on away. audio etc

_Results_
- [x] Tapak slideshow intro image or intro video
- [x] Tapak slideshow unlimited
- [x] FT slideshow intro image or intro video
- [x] FT slideshow unlimited
- [x] Homepage slideshow (WIP) (eg: caption/without, video etc)

- To place as helper text: users need to choose HD YouTube video and full-size, then it will be displayed in full-size accordingly

---

- will test thumbnails / images cropping
- will test fields: create, edit, delete
- will test profiles, listings, maps
- will test promotions : upload 10

---

**Tapak Profile**

- [x] test if 4sq already opens up in new tab and the other external links too

- [ ] Detecting location: refer issue below
> Retrieving current location requires HTTPS. Can you arrange it in LIVE? Reference: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

Testing variables / #notetoself
- _Tapak Urban:_ I put 2 FT Limit/day

---

**WP Admin**
- add [helper texts](https://github.com/iwanikhalid/tapak/issues/17) too while you're at it!

---

## Will post bugs, if any in the comment below.

**Comment by iwanikhalid** [comment]
**UI**

- [ ] Is there a way to make the blog section background act like [tocball.my](http://www.tocball.my/) contact us background? What do you call that? Parallax? If cannot because the concepts are not the same, can we make it background-size: cover; coz repeating it is kinda 90s haha! Btw thanks for the sweet looking arrows for the blog section. I just noticed it, ah love it!

I will keep posting bugs as I notice them instead of dumping in one comment

**Comment by aienzaini** [comment]
Just added the parallax feature to contact us background

**Comment by iwanikhalid** [comment]
Thanks for the parallax fix @aienzaini!!!! In love nyaaaaaaaaa! Ok can we add background: white; kat Explore Our Tapak?

**Comment by aienzaini** [comment]
Done

**Comment by iwanikhalid** [comment]
Sweet, thanks Aien!

**Comment by iwanikhalid** [comment]
Any chance of us getting the homepage About Us section as close as to the PSD version? If cannot, no worries and do tell me the probs so we'll learn not to do that kinda design mistakes anymore haha

![homepage-about-us-font](https://cloud.githubusercontent.com/assets/751716/15999230/be57f4ba-3176-11e6-8dbb-f6e9393f717d.jpg)

**Comment by aienzaini** [comment]
Strange, mine seems closer to PSD. Let me find out from windows.

<img width="1275" alt="screen shot 2016-06-13 at 2 57 47 pm" src="https://cloud.githubusercontent.com/assets/5258695/15999293/3c41ddf0-3177-11e6-8175-e0fcf2bed9dd.png">

**Comment by iwanikhalid** [comment]
Ok noted, thanks Aien! I'm on Windows 10, Chrome

**Comment by iwanikhalid** [comment]
- [ ] the tapakImage exceeded a tiny bit from its' container

![tapakimage-exceeded-exploremap](https://cloud.githubusercontent.com/assets/751716/15999768/8b47218c-317a-11e6-8fd9-8ccc74e84d0b.jpg)

Just in case this bit is important: the size of that image uploaded was 960x960

**Comment by iwanikhalid** [comment]
- [ ] Can you check Tapak Profile > Social Links? I added 4sq but it ain't appearing

![tapakimage-exceeded-exploremap](https://cloud.githubusercontent.com/assets/751716/15999930/8ad3ff76-317b-11e6-8465-929845930165.jpg)

Just in case this bit is important, I created the Tapak without 4sq at first. It was edited later

**Comment by iwanikhalid** [comment]
@aienzaini Homepage > About Us font looks legit now!! Alhamdulillah just the padding left and we're done with that

**Comment by aienzaini** [comment]
Fonts are fixed. There seems to be loading issue in Windows.
Tapak logo on google maps infowindow position also fixed.
4sq icon is now appearing.

**Comment by iwanikhalid** [comment]
Oops, I looked at the wrong section of the 4sq. haha. tq for the fix. I've ticked the 4sq and Tapak logo bugs. Leaving font about us only to do the padding bits

**Comment by aienzaini** [comment]
Ooh you consider the huge padding after the logo and in between the image as bugs? You sure?

**Comment by iwanikhalid** [comment]
Hahahaha I would like to agree with you but yes, I think I agree with you. The huge padding in PSD is rather too _hipsturrr_

I will deal with Nadiah later about this!

**Comment by iwanikhalid** [comment]
This is a test for single slide on Tapak profile using Intro (Image) and Intro (Video) fields in WP Admin

Results: Video is appearing, Image isn't. Image selected is 960x960

URL: [http://52.163.95.207/tapak/tapak/tapak-urban/](http://52.163.95.207/tapak/tapak/tapak-urban/)

**Comment by aienzaini** [comment]
If you have the video, the image wont appear.
If you have the image, the slideshow wont appear.

These are the rules. Let me know if you want to change it.

**Comment by iwanikhalid** [comment]
Hm, okay juga that rule. Let's keep that

**Comment by iwanikhalid** [comment]
I've removed the video, the image tak appear pun?

**Comment by aienzaini** [comment]
Just fixed it. Applied the wrong variable.

**Comment by iwanikhalid** [comment]
Ok single intro and slideshow works awesome for Tapak Profile. Just two tiny bits of concern

- The image below (from the left) 
- - single video. Nice crisp video compression. No orange bar below it
- - slideshow video on its' own. Nice crisp video compression. An orange bar appears below it
- - slideshow video with another slide (image). Lossy video compression. An orange bar appears below it

![tapak-profile-slideshow](https://cloud.githubusercontent.com/assets/751716/16000641/1aef1646-3180-11e6-9712-3a28f7709d2f.jpg)

- [ ] Let's remove the orange bar altogether

This is not a bug just a question, why the video slide pecah2 when the slideshow has another slide in it?

**Comment by aienzaini** [comment]
Emmm does not happen to me? Youtube knows how to arrange the quality based on your connection speed so it could be something wrong with your internet.

**Comment by iwanikhalid** [comment]
Yeah I noticed just the still screenshot is lossy but the actual video is okay. Thanks for the orange bar fix!

**Comment by iwanikhalid** [comment]
@aienzaini if no intro image/video and no slideshow, the profile will turn to this http://52.163.95.207/tapak/tapak/tapak-urban/ - I suppose after removing the orange bar. What should we do? Make Intro (Image) as a required field?

**Comment by aienzaini** [comment]
Refresh, i added a placeholder when there is nothing to show.

**Comment by iwanikhalid** [comment]
This is prolly trivial.
Hover states for Tapak Profile > Waze, 4sq, Social icons should be red. You wanna change that or leave as it is (opacity change on hover, whichever is okay)

If opacity chnage on hover, let's have that on 4sq and waze too

**Comment by aienzaini** [comment]
Opacity change on hover = DONE.

**Comment by iwanikhalid** [comment]
**Food Truck Profile**

Just gonna touch a bit on logic here as I do testing. You may ignore it if you haven't added it in okay

I just began creating FT starting with Mat Rock. Mat Rock just signed up on Tapak and he hasn't booked any Tapak.

- [ ] Mat Rock isn't supposed to appear in Homepage or Tapak profile under "ALL" tab/category ---- until he booked a tapak

According to User Specs, **only Admin** can categorize FT under **Featured** and **Popular**. Whereas the category **All** is the default category for any newly created FT. 

- [ ] For UX sake, should we auto tick **All** by default. This is the screenshot of Mat Rock while and after being created.

![ft-profile-categories](https://cloud.githubusercontent.com/assets/751716/16001833/010da092-3187-11e6-865b-ef539d493c11.jpg)

**Comment by iwanikhalid** [comment]
**Intro image / video & Slideshow for Tapak & FT**

All seemed to work awesome. Have tried with different combinations, have tested for everything (eg: mouse on, mouse off, video stop/play etc) and insyaAllah, all good. 

#notetoself: To place as helper text: users need to choose HD YouTube video and full-size, then it will be displayed in full-size accordingly

---

Just one minor, super minor thing. If can be fixed, would be great. If cannot, no problem

- [ ] **Try to recreate this bug**: Go to http://52.163.95.207/tapak/food-truck/mat-rock-special-ayam-goreng-kunyit/ and play the dog video, wait until it's done playing and make sure your cursor is not on the video. After the video stopped playing, the slideshow won't resume looping automatically, you have to move your cursor back on the slide and off it, then it will loop again

**Comment by iwanikhalid** [comment]
**Booking**

Can you check Booking? I've booked a slot for Mat Rock on Tapak Urban  from 13 - 13 June, meaning 1 day only. WordPress date/time seems to be okay

> Universal time (UTC) is 2016-06-13 11:08:37. Local time is 2016-06-13 19:08:37.

If this is about logic that hasn't been added, you can disregard this until you've added the logic

**Bugs**
- [ ] Mat Rock is not appearing in http://52.163.95.207/tapak/tapak/tapak-urban/ (Filter: Tapak Urban)
- [ ] On [Mat Rock FT Profile](http://52.163.95.207/tapak/food-truck/mat-rock-special-ayam-goreng-kunyit/), only Now should be displayed in Find Us Here

**Comment by aienzaini** [comment]
I have removed FT All categories - easier to manage from logic standpoint.

**Comment by iwanikhalid** [comment]
Alrighty @aienzaini let me know when it's uploaded and I can continue testing! And if the stuffs I mentioned above pun need logic update, just holla me and we can cancel the bugs above and I'll redo testing

**Comment by iwanikhalid** [comment]
**FT Profile > Find us here**

- [ ] Any chance for us to get UI close to the PSD? The Upcoming/Now tags look kinda small on website. The other differences like thumbnail size, font size, column size etc no prob as there can't possibly be a pixel perfect PSD-web conversion
- [ ] I would love the Find us Here section to end at the same line as the Social Icons on the right. If more than that, let's include a [CSS-Fade-Out-Effect](https://css-tricks.com/examples/ReadMoreFade/)

Below is a comparison this section on PSD & website

![find-us-here-web-psd](https://cloud.githubusercontent.com/assets/751716/16006589/7d1be630-31a0-11e6-890c-2b0da98182c8.jpg)

I nak Maghrib, makan and terawih jap. Be back by 10.30pm insyaAllah

**Comment by aienzaini** [comment]
All fixed. Ready for you test again.

**Comment by iwanikhalid** [comment]
@aienzaini  sweeeeeeeeeeet. Thanks! Ticked all :dancer:

**Comment by iwanikhalid** [comment]
Next issue, still on **Booking**

Truck Filter: Tapak should show the NOW or UPCOMING booking? I think only NOW!

**Comment by iwanikhalid** [comment]
**List of Food Trucks on Tapak Profile**

I totally missed this tiny information. I've already written it in the [Design Brief](https://docs.google.com/document/d/1ExxbQZcbDgcKobdv_GcokHDKan0hO-3NbLxwYa9Pzn8/edit) but I forgot to cross check as I was checking the website way earlier on. 

Here it is as per PSD
![tapak-profile-list-of-food-trucks](https://cloud.githubusercontent.com/assets/751716/16014663/cefc08f8-31c4-11e6-90ab-96619998149c.jpg)

- [ ] So on Tapak Profile, the tabs for List of Food Trucks should be Now and Upcoming **not** All, Popular and Featured. Those can be removed on Tapak profile
- [ ] And secondly, in the Truck Filter for Tapak Profile only, we have another filter called When: Now & Upcoming

Then only this listing makes sense! No wonder just now I ter pening sekejap. Anyway if you have any ways to improve this, please go ahead okay.

---

Still regarding List of Food Trucks on Homepage & Tapak profile: **minor UI bug**

- [ ] Check out filter that has a checkbox, the label goes to a new line instead of next to the checkbox

![list-of-ft-filters-checkbox-bug](https://cloud.githubusercontent.com/assets/751716/16014880/c20d2c7a-31c5-11e6-9a24-5a0aaa4f0917.jpg)

**Comment by iwanikhalid** [comment]
**Bug on exploreOurTapakMap truck info box**

- [ ] Looks like we need to truncate that address again. Make it stop at the second line maybe. 

InsyaAllah Tapak name won't be longer than this, at 2 lines. So address pun we cut at 2 lines je

![need-to-truncate-that-address-again](https://cloud.githubusercontent.com/assets/751716/16015151/ff437b84-31c6-11e6-9cbb-c87c92da9231.jpg)

**Comment by iwanikhalid** [comment]
**Bug on List of FT Tabs (a.k.a Categories)**

Remember yesterday, you updated the logic: don't show FT in listing "_All_" unless it has a booking, 

- [ ] Should we add that logic to "Featured" and "Popular" too? Coz now Dr Brew is listed in Featured while it doesn't have a booking yet

![no-booking-no-show](https://cloud.githubusercontent.com/assets/751716/16016424/9527b498-31cd-11e6-8cc0-0fdd5aeef98a.jpg)

The short rule to remember is: no booking, no show bruh! Ok sorry I think I dah hyper and need to sleep now. Bye, continue esok!

**Comment by iwanikhalid** [comment]
Last one, sorry...

- [ ] Can we change the text Now on this [ribbon](http://52.163.95.207/tapak/wp-content/themes/tapak/images/ribbon-now.png) to Today. Baru ngam with this [fix](https://github.com/iwanikhalid/tapak/issues/23#issuecomment-225631901)

**Comment by aienzaini** [comment]
Can you help to get Nadiah to update the text? The PSD is not editable for the text.
![ribbon-now](https://cloud.githubusercontent.com/assets/5258695/16032189/2b7961ae-3236-11e6-9d17-5f9392cba1d7.png)

**Comment by aienzaini** [comment]
As for the FT filter, are we still keeping Featured + Popular? I thought earlier you mentioned to change that to Today + Upcoming?

**Comment by iwanikhalid** [comment]
I've unchecked task no 1 and 2 on this [post](https://github.com/iwanikhalid/tapak/issues/23#issuecomment-225631901). The Today and Upcoming affect the Tapak profile only not the Homepage. Is that doable @aienzaini

**Comment by iwanikhalid** [comment]
Can you help to get Nadiah to update the text? The PSD is not editable for the text.
![ribbon-now](https://cloud.githubusercontent.com/assets/5258695/16032189/2b7961ae-3236-11e6-9d17-5f9392cba1d7.png)

> @aienzaini you can find the PSD in Gdrive\Tapak\Food Truck Profile PSD\food-truck-profile-today

**Comment by aienzaini** [comment]
@iwanikhalid the text is not editable in the PSD. I have the PSD with me.

**Comment by iwanikhalid** [comment]
@aienzaini In that newly created PSD there's only the ribbon and the word today. Do you want me to PNG it for you instead?

**Comment by aienzaini** [comment]
Opps sorry, thought you were saying, check in the PSD. Dont worry i will cut it.

**Comment by iwanikhalid** [comment]
Bro @khairulfathi in Tapak [profile](http://52.163.95.207/tapak/tapak/tapak-urban/), we want to detect user's location and retrieving current location requires HTTPS. Can you arrange it in LIVE? 

Reference: 
> https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by khairulfathi** [comment]
Yes, definitely. But please ensure there's an alternate plan in case it
might sometimes to setup.

**Comment by iwanikhalid** [comment]
Alright, roger bro @khairulfathi

**Comment by aienzaini** [comment]
@khairulfathi Can we enable https in the dev server?
@iwanikhalid Alternatively, we should display from location input box that web visitor can search and get location from. This however requires some times to be developed.

**Comment by iwanikhalid** [comment]
Oh yeahhh @aienzaini that is a smart suggestion! Didn't think of that

**Comment by khairulfathi** [comment]
@aienzaini hurmm maybe, I can use self signed certificate but it will take sometimes to configure. I'm behind firewall right now and can't access server rdp. insya-Allah I will try by tonight.

**Comment by khairulfathi** [comment]
My bad, ter 'Close and Comment' !

**Comment by iwanikhalid** [comment]
No prob bro @khairulfathi  hehehe

**Comment by khairulfathi** [comment]
@aienzaini https enabled. But since its a self-signed cert, you may need to manually import the following cert into local PC. Otherwise any browsers will give warning which a bit irritating but still can proceed nevertheless. 
[server.zip](https://github.com/iwanikhalid/tapak/files/317599/server.zip)

**Comment by iwanikhalid** [comment]
Cool!!!!!!!!!!!!! The location thingy works for me too! Cayalah @aienzaini and @khairulfathi 

We are closing this thread for good!
