### ISSUE TITLE
PSD-Web Inconsistencies

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#24]
@aienzaini 

This website is supposed to be like 'big' - you know like _hipsturr_ concepts these days which I don't necessarily agree with all the time but yes, that was the requirement therefore Nadiah tried her best to design as close as possible to get the big feel - yeah, there are some inconsistencies here and there in her PSD as she's new to this as well like the About Us which definitely needed to be adjusted during dev.

Anyways, how do we best deal with this? Do I list down the changes now in this thread or later just before we do mobile design?

I'll show you one example

- [x] Noticed how our web version List of Food Trucks is kinda shrunk compared to PSD. 

We got the container size the same already as Promotions look identical

**As seen on PSD**

![web-psd-comparison-psd](https://cloud.githubusercontent.com/assets/751716/16016054/6512457c-31cb-11e6-950c-c067b0127758.jpg)

**As seen on Web**

![web-psd-comparison-web](https://cloud.githubusercontent.com/assets/751716/16016058/6997728e-31cb-11e6-823c-7541eb480430.jpg)

I understand that this might also be related to browser compatibility or screen resolution etc so I'll wait to hear your comments first on to list down now or later

**Comment by aienzaini** [comment]
We are stuck with promotions width which is 1171px. Best to follow that for now. My only worry is that iPad has 1024px width on landscape so we might need to squeeze the promo size a bit.

That means mobile responsive will have:

1. Phone - portrait/landscape.
2. Tablet - portrait/landspace (normally i will follow desktop styling for this).

Mobile responsive is coming today.

FYI, i have fixed the truck grid.

**Comment by iwanikhalid** [comment]
Yep, I agree with following 1171px! And agree too on squishing promo on iPad landscape

And thanks for fixing the Truck grid!! Lovely! If there are any other UI stuffs to take note, I will post below

**Comment by iwanikhalid** [comment]
**This is regarding the Find Us Here & Contact Info sections on FT Profile**

![make-this-section-ft-profile-bigger](https://cloud.githubusercontent.com/assets/751716/16040809/8b32b022-3264-11e6-882c-8d6af8615d83.png)

Everything here works perfectly. 

- [ ] I was just wondering if we can and should make the sections look 'bigger', speak 'louder' - in other words, I think we need to adjust the fonts size in the headings and content. And probably adjust the padding here and there a bit. The social media icons too as they slightly differ in size when you compare PSD to Web. 

I wonder if it's due to Nadiah's way of Photoshopping. Do let me know so that we can improve from our side.

**Comment by iwanikhalid** [comment]
- [ ] Let's jom beautify the blog posts carousel a bit to make it look even more awesome than it already is

![blog-section-fix](https://cloud.githubusercontent.com/assets/751716/16067189/aba270bc-32ec-11e6-8238-5891b0abddd6.jpg)

**Comment by iwanikhalid** [comment]
Thanks @aienzaini  for the fonts fix for Find Us Here/Opening Hours and thanks for fixing the blog section too.

One last thing about the blog section, can we truncate the post title at 3rd line?

**Comment by iwanikhalid** [comment]
Blog posts carousel is awesome!

- [ ] One last thing about that, can we truncate the post title at 3rd line?

**Comment by iwanikhalid** [comment]
Ok. We're closing this for the time being. All issues resolved
