### ISSUE TITLE
Testing & Debugging 3 (User Roles)

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#27]
Starting a new topic to compile user roles, and anything more backend specific & system related testing and debugging results and bugs

---

**FTOs accesses**
7senarai@gmail.com @ matrock ; 7senarai@gmail.com
Salam Noodles @ 1ch0pme_ ; nadsulaiman@gmail.com 
Dr Brew @ br3wme_ ; ceramahme@gmail.com

**Comment by iwanikhalid** [comment]
Since we've confirmed in the Testing & Debugging 1 & 2, Promotions and Bookings generally work fine, I have trashed the testing content under them to start a new one. Mat Rock's profile and everything related to it has also been removed.

So far, bookings & promos logic is spot on. I see no food trucks in listing, no bookings anywhere, and no promos anywhere. Now we are ready for the next testing tomorrow

---

We are going to simulate a real situation on Tapak's website. Since we don't have a registration form for FTO yet, we'll create one below.

user: fto_matrock / pwd: matrock

Testing will begin tomorrow and any bugs will be posted here.

**Comment by iwanikhalid** [comment]
@aienzaini I saw the updated fields in FT and Tapak from /wp-admin. Awesome!

Let's just quickly run through the rental rates

1. There are only 2 types of FT weight
- equal/less than 3 tonnes
- more than 3 tonnes

2. Every Tapak has a it's own unique daily / bi-weekly / monthly rental rate for trucks
- equal/less than 3 tonnes
- more than 3 tonnes

3. When booking, FT can book
- daily
- bi-weekly
- monthly

> We can do this selection manually instead of system automatically detect it's a bi-weekly or monthly booking since we are not integrating payment gateway yet. You can refer to my [cheat](https://app.mockflow.com/view/413c9aa74e69e1d70e199544e25b2546) wireframe under Book a Slot. I think you can suggest a better idea than my silly cheat

**My questions are**
1. Where should the rates fields be? In FT or in Tapak? Currently, I see them in FT

2. In the Booking section for Admin and FTO, are we able to calculate each booking rental so that it's easier for them to pay and manage in real life? 

If I'm not mistaken this is like the key needs of having this website go live quickly, to help them ease the booking and payment process. Currently everything is done manually and by "janji mulut" which causes a lot of mismanagement on the ground

**Comment by iwanikhalid** [comment]
Thanks @aienzaini for auto calculation and dah nampak rental rates in Tapak. How FTO nak set their FT weight? I saw one field in FT called Truck Type *  but it's not editable

**Comment by iwanikhalid** [comment]
I tried to register as FTO and received a "Invalid Email Address" error

![ft-reg-form-bug](https://cloud.githubusercontent.com/assets/751716/16175845/d8bdbabc-362e-11e6-89c5-cfab10ecf7c2.jpg)

**Comment by aienzaini** [comment]
@iwanikhalid Can you also check with Khairul if the website is setup to send email? I can't seem to send one.

**Comment by iwanikhalid** [comment]
Bro @khairulfathi can you check if the server is setup to send email?

**Comment by iwanikhalid** [comment]
Bro @khairulfathi if php_mail() isn't available on this server. We can use SMTP too. I need the host, username, password, port and type of encryption (ssl or tls or none). I tried using gmail with no avail coz they had made it very [leceh](http://www.wpsitecare.com/gmail-smtp-settings/) recently.

**Comment by khairulfathi** [comment]
@iwanikhalid haven't setup email service on that server. please use this one instead : 

Server : smtp.sendgrid.net
User : azure_d6e6ab819095eccf2f4b074136f93eee@azure.com
Password : 3Jm075AUS2xDrWX

**Comment by iwanikhalid** [comment]
Ok success! Thanks bro @khairulfathi

**Comment by iwanikhalid** [comment]
**Bugs/FIxes for @aienzaini**

_Food Truck CPT FIelds_
- [ ] This is convenient to have but not necessary - For FTOs, in the FT title, can we retrieve their Brand Name (from Profile, we asked for this during registration) automatically
- [ ] Remove Company/Business Name from FT fields as we have this in Profile or alternatively, we can we retrieve this field from Profile?
- [ ] Can we allow FTO to post only 1 FT at this stage? 
- [ ] Remove helper text "This is visible in FT profile page" on Fax No coz I think we tak display it. 

---

**Iwani tests archive | testing so far as of 3:29pm**

_FTO: Registration & Creating a Profile_
:heavy_check_mark: Registers as a FTO via FT Reg Form, Matrock is born!
:heavy_check_mark: Receives email to insert password
:heavy_check_mark: Login and have option to change username
:heavy_check_mark: Created a FT & Submitted for Admin's review
:heavy_check_mark: Admin approves, Profile is live but not yet listed of course
:heavy_check_mark: Add promotion

_FTO Booking_
:heavy_check_mark: Added a couple of random bookings, amount is showing, cool!

_FTO Promo_
:heavy_check_mark: Added a couple of random promos, all cool!

_Admin Tasks_
:heavy_check_mark: Review and publish FTO profiles
:heavy_check_mark: Created Tapak profile
:heavy_check_mark: Reviewed and published bookings! Amount is showing up, cool!
:heavy_check_mark: Reviewed and published promotions

---

Taking a break: Next will be testing Menu, Slideshow, List of FT (final test)

**Comment by iwanikhalid** [comment]
- [ ] Promotions on Food Truck should only show the FT's promos, not others http://52.163.95.207/tapak/food-truck/dr-brew/

**Comment by iwanikhalid** [comment]
- [ ] Promotions on Tapak should only show promos by FT on that Tapak kan? So Mat Rock promos shouldn't show up on http://52.163.95.207/tapak/tapak/tapak-bersaudara-bandar-baru-bangi/

Or is it showing coz Mat Rock does have upcoming bookings on Tapak BBBB?

**Comment by iwanikhalid** [comment]
# Bugs/Fixes for @aienzaini to squash

**_WP Admin Notification_**
- Can we disable Admin Columns Pro plugin notification for FTOs?

**_Food Truck_**
- [ ] We need to allow FTOs to edit their FT Cuisines and Price  [ability create new and tick existing]

**_Slideshow_**
- [ ] We need to allow FTOs to edit their Slideshow

**_Promotions_**
- [ ] Let's remove Admin moderation for Promotions posts
- [ ] Promotions on Tapak should only show promos by FT on that Tapak kan? So Mat Rock promos shouldn't show up on [Tapak BBBB](http://52.163.95.207/tapak/tapak/tapak-bersaudara-bandar-baru-bangi/). Or is it showing coz Mat Rock does have upcoming bookings on Tapak BBBB?
- [ ] Promotions on Food Truck should only show the FT's promos, not others http://52.163.95.207/tapak/food-truck/dr-brew/

**_Menu_**
- [ ] We need to allow FTOs to edit their Menu Categories & Classification  [ability create new and tick existing]
- [ ] Menu is not showing somehow. Check out Dr Brew's profile. They should have 4 drinks on the menu http://52.163.95.207/tapak/food-truck/dr-brew/ #mayday
- [ ] Let's remove Admin moderation for Menu posts

**_Tapak_**
- [ ] For Tapak custom post type, is it possible to change its' WP Title placeholder from "Enter title here" to "Enter Tapak name". If this can be done, cun gila. If not, no problem

**_CSS_**
- [ ] Add this code in CSS `` .ftLogo img `` to ensure when a transparent logo is added, we have white background! Example of unpretty [floating logo](http://52.163.95.207/tapak/tapak/tapak-singapura/) without bg

---

**Iwani test archives**

:heavy_check_mark: Slideshow homepage 
:heavy_check_mark: Slideshow Tapak
:x: Slideshow FTO | need to retest
:x: Menu | need to retest

**Comment by iwanikhalid** [comment]
# Super duper final bugs to squash @aienzaini

**_Admin Power_**

- [ ] At the moment, my admin access isn't allowed to do this. Can you allow Admin to create/add new 

- FT: Cuisines & Price
- Menu: Category & Classification. 

---

**_Slideshow_**
- [ ] FTO can now edit Slideshow. Alhamdulillah but we need to hide (with CSS maybe) the Tapak selection. Check this [out](http://52.163.95.207/tapak/wp-admin/post-new.php?post_type=slideshow) to see what I mean. 
- [ ] Is the homepage slideshow OK for you in terms of speed between each slide and when video is playing, slide will stop looping. Mine has gone haywire since I added Matrock's slideshow

**_List of FT_**

`Filter seems buggy. Only Filter: Cuisine is working as expected`
- [ ] I think Filter: Search Food seems buggy. Try search for "kunyit", only Mat Rock should appear kan
- [ ] I think Filter: Price Range seems buggy. FTs are appearing not according to selected price range
- [ ] I think Filter: Tapak seems buggy. FTs are appearing not according to selected tapak

---

Referring to the image below, there are 2 bugs connected to it

![list-of-ft-bug-height-missing-info](https://cloud.githubusercontent.com/assets/751716/16201128/cd1ee770-3742-11e6-80e1-a39fc4944124.jpg)

- [ ] Height of List of FT box is not even
- [ ] Dapurnomnom is listed because it does have an Upcoming booking. I believe we should write something there in the red circled area. How about ```Click to view our Upcoming Tapak```

**_Promotions_**

- [ ] Dr Brew should have 3 ongoing promotions. In [Tapak BBBB](http://52.163.95.207/tapak/tapak/tapak-bersaudara-bandar-baru-bangi/), we are showing 2 promotions only in List of FT and Promotions

**_Menu_**

- [ ] Menu on the right column will not show RM in the price. Check out [Mat Rock](http://52.163.95.207/tapak/food-truck/mat-rock-special-ayam-goreng-kunyit/) and [Dr Brew](http://52.163.95.207/tapak/food-truck/dr-brew/)

- [ ] I think we need to add some cropping logic to the menu photo. And then link it to full image on lightbox. Check out [Salam Noodle](http://52.163.95.207/tapak/food-truck/salam-noodles/) menu breaking apart. Even (http://52.163.95.207/tapak/food-truck/mat-rock-special-ayam-goreng-kunyit/) too is kinda panjang. 

One way to solve this is to strictly ask them to upload: 505px x 199px according to Nadiah's design

The menu could possibly look beautifully formatted like this

![menu-blocks](https://cloud.githubusercontent.com/assets/751716/16202230/602fa19a-3747-11e6-86b1-dd318cd08a0e.jpg)

----

- [ ] Can we disable Admin Columns Pro plugin notification for FTOs. Use this account to see it ```nadsulaiman@gmail.com @ 1ch0pme_  ```

![admin-columns-pro](https://cloud.githubusercontent.com/assets/751716/16202729/976cb664-3749-11e6-9644-689b40ec8590.jpg)

- [ ] Can we allow FTO to post only 1 FT at this stage? In case this would cause other bugs to the other Custom Post Types, we can dismiss this. Admin just need to ignore if FTO try to post more than 1 FTs.

**Comment by iwanikhalid** [comment]
@aienzaini Thanks for the fixes above Aien. I'm going through one by one yayyers.

Btw, yang Dr Brew promo tu yang [ni](http://52.163.95.207/tapak/wp-admin/post.php?post=622&action=edit) 21 - 30 June 2016

**Comment by iwanikhalid** [comment]
Alhamdulillah, we're done with this. It's a wrap!!!! (on github!)
