### ISSUE TITLE
Clean up Tapak.co

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#30]
Hi @aienzaini I got the instruction to delete Tapak.co mock content as they are starting to have registrations already. 

Can you help me identify the mock/test content you added on the below and delete them

- Food Trucks
- Promotions
- Menu
- Booking
- Users

Thanks much!

**Comment by iwanikhalid** [comment]
I dah delete most of your testing @aienzaini nasib baik ada author so I know those by aien boleh deleted. Haha. However there's one FT I can't decipher whether it's mock content or real - Wok-It by info.gccmgs@gmail.com - is that you Aien?

**Comment by aienzaini** [comment]
So sorry! I am very2 busy lately, tak sempat nk tengok. Nope, not that i know of.

**Comment by iwanikhalid** [comment]
It's okay @aienzaini I thought so too. Anyway this task is done. Yay! Thanks!
