### ISSUE TITLE
Menu: Menu Item not appearing if it's in a newly created category

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#31]
Hi @aienzaini 

Tapak found the first bug in the website as they've started to fill up the content.

Menu item isn't displaying if it's under a newly created category. For example, Dr Brew's profile on dev site is http://52.163.95.207/tapak/food-truck/dr-brew/

There is supposed to be a new category under menu called Tacos and a menu item called 
Nachos with Guacamole under it

Can you have a quick look at it?

Do keep track of the time taken to fix the bug okie! I haven't discussed the fees for Post Guarantee Period. Let's just record the time first for now. Hope that's okie!

**Comment by aienzaini** [comment]
Hi @iwanikhalid 

Initially, only recognized Menu Categories will be shown in front - this is to ensure we can sort the category properly.

I have changed this feature by adding another field within Menu Categories - Sequence. This sequence will determine the sorting of menu categories at the front end. Now you are free to add Menu Categories as you like but don't forget to sort them! Else it will be shown as the first one.

Updated file: *single-food-truck.php*

**Comment by iwanikhalid** [comment]
Thanks @aienzaini will test this in a bit. I saw it implemented in live site.

Should we disregard the dev site from now onward and just work on live site when they are fixes? What's your thoughts? And how are we going to maintain the files via github/commit

**Comment by iwanikhalid** [comment]
Hi @aienzaini I've added the sequences from 1 - 9 for all Menu Categories. Unfortunately Flaming Wheels ain't showing up their menus https://www.tapak.co/food-truck/flaming-wheels/

**Comment by khairulfathi** [comment]
@iwanikhalid I've reverted the one in live site. Can you please commit the code first so I can test in dev site? Thanks.

**Comment by aienzaini** [comment]
@khairulfathi I will commit the file that has been changed.

Anyway i can't seem to list directory and download files from dev site FTP. Can you please help to check?

**Comment by iwanikhalid** [comment]
Ohhh no wonder you made the changes on live site terus. The dev site tak work eh @aienzaini 

Bro @khairulfathi can you take a look at the dev site nanti bila free? Otherwise should we just continue to work on live site? Then we can create another branch untuk live site kat github ni or something

**Comment by iwanikhalid** [comment]
Flaming wheels menu look so yummmyy btw! Nanti bila dah ada banyak2 sub-cats nanti lagi best hee!

**Comment by khairulfathi** [comment]
@aienzaini let's test directly in production since there aren't many visitors yet. i'm having difficulty to configure network and firewall issues to fix the FTP since the machine is being shared with some other of my projects.

**Comment by khairulfathi** [comment]
Please let me know if you've fixed this in production. Thanks.

**Comment by aienzaini** [comment]
@khairulfathi I have just fixed this in live environment. Please let me know if it doesn't work still as i couldn't see any published FT available.

**Comment by iwanikhalid** [comment]
I've helped to test this out. Seems to be working now. I put butter rice under category called NASI @ https://www.tapak.co/food-truck/flaming-wheels/

Can you confirm nanti bro @khairulfathi tqqq!

**Comment by khairulfathi** [comment]
Cool, seems working right now. Thanks for the help.

**Comment by iwanikhalid** [comment]
Ok cool! I'm closing this alrighty!
