### ISSUE TITLE
Can't Publish Booking in Production

### ISSUE THREAD

**Issue by khairulfathi** [iwanikhalid/tapak#36]
Assalam,

Bro @aienzaini , all bookings in December will turn back to Draft when I click Publish. No problem to change to Pending Review though. Do you mind to have a quick look? Or even better if you can guide me how to debug wordpress, at least to see what's the underlying error message.

Thanks.

**Comment by aienzaini** [comment]
Salam @khairul.fathi,

If you are not administrator, then you cannot publish the bookings (and
same goes to food truck).

This is a custom feature built for the site.


Aien / Ahmad Azarinurazie Mohd Zaini
mobile +6 016 3333 078  skype ahmad.azarinurazie

**Comment by khairulfathi** [comment]
@aienzaini I am the administrator and all these while its working great. Starting December, there are few records that have this issue. If you login to live site, there's a booking by AHRXpress for 16/12/2016 under Pending Review. You can publish this booking to simulate the error.

![booking_problem](https://cloud.githubusercontent.com/assets/12525078/21040411/b678bcee-be1f-11e6-84d1-b59bbbbf6ab2.jpg)

**Comment by aienzaini** [comment]
@khairulfathi I just fixed the issue. Code problem. The FT has reached maximum booking number for one of the day.
