### ISSUE TITLE
Homepage Slideshow > Video not stretching out in full width

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#7]
Since we're using YouTube to host our slideshow videos, how can we stretch it to fill the whole slideshow?

Check this example out http://tonyromas.com/menu/

**Comment by iwanikhalid** [comment]
@aienzaini How do we ensure the video on slideshow will play in full width? Can we even manipulate YT video to blow up to fill the whole slideshow container?

**Comment by aienzaini** [comment]
I have made it full width. Check it out!
